### PR TITLE
Update screenshots

### PR DESCRIPTION
**Pull request by dgdavid**
## Problem

After latest changes, screenshots show in the README are outdated

## Solution

* Update screenshots
* Display them in groups of two
* Collapse all but _Product selection_ and _Overview_

## Screenshots

| README by default | README after user asks for more screenshots | README after user scrolls down |
|-|-|-|
|Screen Shot 2022-12-12 at 14 55 30 | Screen Shot 2022-12-12 at 14 55 36 | Screen Shot 2022-12-12 at 14 55 42 |

---

Slightly related to https://github.com/yast/d-installer/pull/321 and  https://trello.com/c/GJjb5qTk (internal link).

### CODE REVIEW

**Comment by dgdavid** [comment]
> I think I liked more the previous version with prominent screenshots. Now they are kind of hard to spot... and screenshots sell.

I see. But the problem is that they push the content too far down, I fear.

I'll try something else.

**Comment by dgdavid** [comment]
Which do you like more?

| Two screenshots per row | Three screenshots per role |
|-|-|
| Screen Shot 2022-12-12 at 14 20 07 | Screen Shot 2022-12-12 at 14 19 44 |

Another option is to put only one screenshots at the beginning (the overview) and the rest in a section.

**Comment by ancorgs** [comment]
I like the left one (two screenshots per line) but only with the first line (product selection and overview) visible at first sight. And then the others collapsed below.

**Review by ancorgs — APPROVED** [review]
LGTM

**Review by joseivanlopez — APPROVED** [review]
LGTM

**Pull request merged**
